everx-labs/ever-sdk

Jenkinsfile

Add cleanup post stage to avoid disk space consumption on workers.

addclenup to each stage

---

ton_abi/src/contract.rs
ton_abi/src/error.rs
ton_abi/src/event.rs
ton_abi/src/function.rs
ton_abi/src/json_abi.rs
ton_abi/src/lib.rs
ton_abi/src/tests/full_stack_tests.rs
ton_abi/src/tests/test_contract.rs
ton_abi/src/tests/test_encoding.rs
ton_client/client/src/tests/mod.rs
ton_sdk/src/contract.rs
ton_sdk/src/tests/test_contract.rs

1. Refactor update_data (partially move to abi)
2. Events tests
3. Predefined id in ABI

Test events

---

ton_client/client/src/contracts/mod.rs
ton_client/client/src/types.rs

Get boc hash

---

ton_client/client/Cargo.toml
ton_client/platforms/ton-client-node-js/Cargo.toml
ton_client/platforms/ton-client-react-native/Cargo.toml
ton_client/platforms/ton-client-web/Cargo.toml

Version 0.19.0

---

ton_client/platforms/ton-client-web/Cargo.toml

Added options for WASM binary size reducing

Wasm size reduce

---

ton_client/platforms/ton-client-react-native/build.js

Incomming message and stream are using close event to resolve promise

Fix react native build script

---

CHANGELOG.md
ton_client/client/Cargo.toml
ton_client/client/src/client.rs
ton_client/client/src/interop.rs
ton_client/client/src/tests/mod.rs
ton_client/client/src/types.rs
ton_client/platforms/ton-client-node-js/Cargo.toml
ton_client/platforms/ton-client-react-native/Cargo.toml
ton_client/platforms/ton-client-web/Cargo.toml

- parallel requests on different contexts don't block each other. Requests on the same context
remain sequential

Parallel requests

---

Jenkinsfile

Also fixed setting branch parameter for sdk

Deploy RC branches

---

ton_client/client/src/contracts/deploy.rs
ton_client/client/src/contracts/mod.rs
ton_client/client/src/contracts/run.rs

More errors with address and function fields

Error fields

---

ton_client/client/Cargo.toml
ton_client/client/src/client.rs
ton_client/client/src/dispatch.rs
ton_client/client/src/error.rs
ton_client/client/src/interop.rs
ton_client/client/src/queries/errors.rs
ton_client/client/src/queries/mod.rs
ton_client/client/src/queries/tests.rs
ton_client/client/src/tests/mod.rs
ton_client/platforms/ton-client-node-js/build.js

- `client.register_callback` and `client.unregister_callback` functions
- `queries.subscribe_collection` uses callback-based design

1.0.0 subscription callback

---

ton_client/client/src/abi/abi.rs
ton_client/client/src/abi/encode.rs
ton_client/client/src/abi/internal.rs
ton_client/client/src/boc/mod.rs
ton_client/client/src/client/client.rs
ton_client/client/src/crypto/internal.rs
ton_client/client/src/dispatch.rs
ton_client/client/src/encoding.rs
ton_client/client/src/lib.rs
ton_client/client/src/processing/internal.rs
ton_client/client/src/tests/mod.rs
ton_client/client/src/utils/conversion.rs
ton_client/client/src/utils/errors.rs
ton_client/client/src/utils/mod.rs
ton_client/client/src/utils/tests.rs

utils module and `message_id` in results of the abi encode functions

NEW: utils module

---

ton_client/client/src/abi/decode_message.rs
ton_client/client/src/abi/mod.rs
ton_client/client/src/abi/signing.rs
ton_client/client/src/abi/tests.rs
ton_client/client/src/crypto/boxes.rs
ton_client/client/src/crypto/keys.rs
ton_client/client/src/json_interface/modules.rs

FIX: Signer serialization error

NEW: decode_function_body

---

docs/json_interface.md
docs/mod_abi.md
docs/mod_client.md
docs/mod_processing.md
docs/mod_tvm.md
docs/modules.md
ton_client/client/src/abi/decode_message.rs
ton_client/client/src/abi/encode_account.rs
ton_client/client/src/abi/encode_message.rs
ton_client/client/src/abi/internal.rs
ton_client/client/src/abi/mod.rs
ton_client/client/src/abi/tests.rs
ton_client/client/src/abi/types.rs
ton_client/client/src/crypto/mod.rs
ton_client/client/src/json_interface/modules.rs
ton_client/client/src/processing/mod.rs
ton_client/client/src/processing/parsing.rs
ton_client/client/src/processing/process_message.rs
ton_client/client/src/processing/tests.rs
ton_client/client/src/processing/types.rs
ton_client/client/src/tests/mod.rs
ton_client/client/src/tvm/execute_message.rs
ton_client/client/src/tvm/mod.rs
ton_client/client/src/tvm/tests.rs
ton_client/client/src/utils/conversion.rs
ton_sdk/src/contract.rs
tools/api.json

NEW: add safety remarks to json_interface.md

NEW: decode_message_body

---

ton_client/client/src/abi/types.rs
ton_client/client/src/error.rs
ton_client/client/src/json_interface/modules.rs
ton_client/client/src/tvm/check_transaction.rs
ton_client/client/src/tvm/errors.rs
ton_client/client/src/tvm/execute_get.rs
ton_client/client/src/tvm/execute_message.rs
ton_client/client/src/tvm/tests.rs
ton_sdk/src/local_tvm.rs
ton_sdk/src/transaction.rs

- Updated state
- options used
- exit_arg

1.0.0 tvm+

---

CHANGELOG.md
ton_client/client/Cargo.toml
ton_client/client/src/contracts/run.rs
ton_client/platforms/ton-client-node-js/Cargo.toml
ton_client/platforms/ton-client-react-native/Cargo.toml
ton_client/platforms/ton-client-web/Cargo.toml
ton_sdk/src/error.rs
ton_sdk/src/local_tvm.rs

Executor skiped reason checked to return proper error

Executor skipped reason

---

CHANGELOG.md
ton_client/client/src/boc/hash.rs
ton_client/client/src/boc/internal.rs
ton_client/client/src/boc/mod.rs
ton_client/client/src/boc/tests.rs
ton_client/client/src/json_interface/modules.rs

- `boc.get_boc_hash` function for calculating BOC root hash

get_boc_hash

---

ton_client/src/abi/signing.rs
ton_client/src/abi/tests.rs
ton_client/src/crypto/boxes.rs
ton_client/src/crypto/mod.rs
ton_client/src/crypto/tests.rs
ton_client/src/json_interface/crypto.rs
ton_client/src/json_interface/modules.rs

remove_signing_box

---

ton_client/src/debot/dengine.rs
ton_client/src/debot/mod.rs
ton_client/src/debot/tests.rs

Print id of sent message in dengine

---

CHANGELOG.md
docs/mod_net.md
docs/modules.md
ton_client/src/client/client.rs
ton_client/src/json_interface/modules.rs
ton_client/src/json_interface/registrar.rs
ton_client/src/net/errors.rs
ton_client/src/net/mod.rs
ton_client/src/net/node_client.rs
ton_client/src/net/tests.rs
tools/api.json

- `suspend` and `resume` methods in the `net` module for disabling and enabling network activity

1.3.0 suspend

---

ton_client/Cargo.toml

This needed for linked and build ton-sdk for iOS apps

add "staticlib" to crate-type array

---

CHANGELOG.md
api/derive/src/utils.rs
docs/mod_abi.md
docs/mod_boc.md
docs/mod_client.md
docs/mod_crypto.md
docs/mod_debot.md
docs/mod_net.md
docs/mod_processing.md
docs/mod_tvm.md
docs/mod_utils.md
tools/api.json
tools/api.ts
tools/docs.ts
tools/ts-code.ts

NEW: ts-generator includes doc comments in JSDoc format.

NEW: Smart summary and description doc separation.

---

CHANGELOG.md
ton_client/src/json_interface/modules.rs
ton_client/src/net/mod.rs
ton_client/src/net/tests.rs
ton_client/src/processing/mod.rs

- `net.find_last_shard_block` function returning account shard last block ID.

1.4.0 find last block

---

CHANGELOG.md
ton_client/src/error.rs
ton_client/src/processing/errors.rs
ton_client/src/processing/fetching.rs
ton_client/src/processing/process_message.rs
ton_client/src/processing/send_message.rs
ton_client/src/processing/wait_for_transaction.rs
ton_client/src/tvm/call_tvm.rs
ton_client/src/tvm/check_transaction.rs
ton_client/src/tvm/errors.rs
ton_client/src/tvm/run_message.rs
ton_sdk/src/transaction.rs

- Fields `config_servers`, `query_url`, `account_address`, `gas_used` in specific errors data

1.9.0 extend error

---

ton_client/src/json_interface/net.rs

Important Notes on Subscriptions

1.10.0-subscription-doc

---

CHANGELOG.md
docs/mod_abi.md
docs/mod_boc.md
docs/mod_client.md
docs/mod_crypto.md
docs/mod_debot.md
docs/mod_net.md
docs/mod_processing.md
docs/mod_tvm.md
docs/mod_utils.md
ton_sdk/src/contract.rs
toncli/src/api.rs
tools/api.json
tools/api.ts
tools/docs.ts
tools/ts-code.ts

NEW: doc-generator: constructor functions-helpers for enum type variable creation
NEW: toncli api: add new line in the end if api.json

1.10.0-doc-gen-fixes

---

CHANGELOG.md
ton_client/src/debot/sdk_interface.rs

fix function getAccountsDataByHash in debot sdk interface

getAccountsDataByHash fix

---

CHANGELOG.md
ton_client/src/processing/tests.rs
ton_sdk/src/message.rs

- `total_output` field in fees was always 0.

1.16.1 fix total output

---

CHANGELOG.md
ton_client/src/net/iterators/block.rs

Fixed first master blocks search for network start in blocks and transactions iterators

1.18.1 fix iterator

---

CHANGELOG.md
ton_client/src/error.rs
ton_client/src/net/errors.rs
ton_client/src/net/queries.rs
ton_client/src/processing/errors.rs

- Diagnostic fields `filter` and `timestamp` in `wait_for_collection` error

Extend waitfor error

---

CHANGELOG.md
ton_client/src/net/server_link.rs
ton_client/src/net/tests.rs

- Deprecated `main.ton.dev` and `net.ton.dev` endpoints are replaced with proper endpoints list

Replace endpoints

---

ton_client/Cargo.toml
ton_client/src/client/wasm_client_env.rs

According to this issue
https://github.com/tkaitchuck/aHash/issues/95

Remove serde feature from wasm-bindgen

---

CHANGELOG.md
ton_client/src/error.rs
ton_client/src/net/mod.rs
ton_client/src/net/server_link.rs
ton_client/src/net/tests.rs
ton_client/src/net/websocket_link.rs

- Information about used endpoint is added to subscription errors.

1.21.3 url in ws error

---

CHANGELOG.md
docs/reference/types-and-methods/mod_crypto.md
docs/reference/types-and-methods/mod_debot.md
docs/reference/types-and-methods/mod_proofs.md
docs/reference/types-and-methods/modules.md
tools/api.json
tools/api.ts
tools/docs.ts

- Documentation generator for app object interface fills documentation from
`ParamsOfXXXAppObject` enum.
- Documentation generator for function with `obj` parameter add this parameter
into parameters section with link to appropriate AppObject interface.

doc gen for app objects

---

Cargo.lock
ton_client/src/net/endpoint.rs
ton_client/src/net/server_link.rs
ton_client/src/net/ton_gql.rs

FIX: out of sync detection on batch query

---

ton_client/src/json_interface/modules.rs
ton_client/src/processing/message_monitor.rs
ton_client/src/processing/mod.rs
ton_client_processing/src/lib.rs
ton_client_processing/src/message_monitor/mod.rs
ton_client_processing/src/message_monitor/monitor.rs
ton_client_processing/src/message_monitor/queue.rs
ton_client_processing/src/tests.rs

NEW: `wait` was renamed to `wait_mode`.
NEW: AtLeastOne & All wait logic was changed

NEW: `FetchWait` was renamed to `MonitorFetchWaitMode`.

---

ton_client/build.js
ton_client/src/processing/errors.rs

It is possible to specify target
Fix warning

VP-94 Fix build script
